### ISSUE TITLE
1.20.1 fabric doesn't show the hit color change ingame.

### ISSUE THREAD

**Issue by TheShadyyOneYT** [femboyPig/HitColor#6]
I'm not totally familiar with hex codes, but I have used them before. it doesn't work at all when I type in a hex code. #0000FF <--- this is blue (https://www.color-hex.com/color/0000ff) on a hex code website I found. But when I save and exit the config, it just simply doesn't work. Am I missing something here? the ingame config just doesn't work at all. I unfortunately can't record a video right now as I'm going on vacation but when I get back, I will show you the issue at hand. **But here is how you re-create it:** Make a new world, (creative mode), grab a pig spawn egg, spawn it, open up mods (mod menu), type in hit, go into the ingame config, type in #0000FF, press save, close the menu, hit the pig, and the color is still the exact same as before. (Alpha set as default which is 32)

**Comment by femboyPig** [comment]
on version 1.20.1 after changing the color in the config you should write the command /hitcolor

**Comment by TheShadyyOneYT** [comment]
is there anyway to allow it work without commands? I was planning on using this in survival, and planned not to use any commands, but if this isn't possible than, I would like to know why if you don't mind me asking.

**Comment by femboyPig** [comment]
it's fixed in version 1.21, but the reason it's still there in 1.20.1 is my laziness.

**Comment by TheShadyyOneYT** [comment]
bruh 💀is it possible to change that via a datapack?

**Comment by femboyPig** [comment]
I don't understand what datapacks and mods have to do with each other.

**Comment by TheShadyyOneYT** [comment]
🤷 just was asking if there is a way to edit it to remove the /hitcolor command without needing it, because as you stated "It's fixed in 1.21, but the reason it's there in 1.20.1 is my laziness." So therefore, is there a way for someone or me to modify it to change that, because I'm trying to make a modpack and make an immersive experience without the need of commands. This mod would be suited towards my modpack (not released) but I cant have any mods be interfering if commands are needed. I was just asking if datapacks or maybe modifying the code would change it to remove that said command. I understand why you don't want to change it in 1.20.1 (not to be mention the code changes in every update) but if something can be done, it would be nice, Even if someone made a datapack compat to remove the command or something. And datapacks could of been a way, I'd assumed. Personally I have no experience in coding whatsoever, but I'm just trying to find a valid solution to this without causing you any issues.

**Comment by femboyPig** [comment]
I will do an update where this will be fixed soon.

**Comment by TheShadyyOneYT** [comment]
sounds good. 👍

**Comment by femboyPig** [comment]
fixed it just now, you can check if you are satisfied.

**Comment by TheShadyyOneYT** [comment]
I will test it right now, and report back asap.

**Comment by femboyPig** [comment]
well

**Comment by TheShadyyOneYT** [comment]
Ok everything works, i will post a video here, the only issue I think is happening is the fire texture isn't displaying on mobs, granted that might be my other mods, but I'm like 70% certain its this mod.

**Comment by femboyPig** [comment]
![image](https://github.com/user-attachments/assets/03b11e85-d5c7-4f50-9bd7-0e9db7497aed)

**Comment by femboyPig** [comment]
![image](https://github.com/user-attachments/assets/19225c88-5f43-4cf9-a385-db32166c1567)

**Comment by TheShadyyOneYT** [comment]
hmm okay, ill take a peak, it most likely is on my part, thanks :) I will figure it out on my end and get back to confirm my suspicions, but other than that it works very well

**Comment by femboyPig** [comment]
👍

**Comment by TheShadyyOneYT** [comment]
thank you for this lovely mod 👍

**Comment by TheShadyyOneYT** [comment]
I found my issue, it was a mod called Blanket Client Tweaks, thank you for bearing with me. Just double checked and everything is working fine.
